spring:
  rabbitmq:
    host: 47.111.165.45
    password: qwerDF@123
    port: 5672
    username: rabbitmqadmin
    virtual-host: /
    publisher-confirm-type: correlated # 设置 Confirm 类型为 CORRELATED 。
    publisher-returns: true #
