spring:
  rabbitmq:
    host: 47.111.165.45
    password: qwerDF@123
    port: 5672
    username: rabbitmqadmin
    virtual-host: /
    listener:
      type: simple # 选择的 ListenerContainer 的类型。默认为 direct 类型
      simple:
        concurrency: 2 # 每个 @ListenerContainer 的并发消费的线程数
        max-concurrency: 10 # 每个 @ListenerCon 允许的并发消费的线程数
#      direct:
#        consumers-per-queue: 2 # 对于每一个 @RabbitListener ，一个 Queue ，对应创建几个 Consumer 。
