#spring:
#  # RabbitMQ 配置项，对应 RabbitProperties 配置类
#  rabbitmq:
#    host: 127.0.0.1 # RabbitMQ 服务的地址
#    port: 5672 # RabbitMQ 服务的端口
#    username: guest # RabbitMQ 服务的账号
#    password: guest # RabbitMQ 服务的密码


#spring:
#  # RabbitMQ 配置项，对应 RabbitProperties 配置类
#  rabbitmq:
#    host: 8.137.16.158 # RabbitMQ 服务的地址
#    port: 5672 # RabbitMQ 服务的端口
#    username: admin # RabbitMQ 服务的账号
#    password: Aq0vaCGhBX # RabbitMQ 服务的密码
#    virtual-host: bthost
#    connection-timeout: 0



spring:
  rabbitmq:
    host: 47.111.165.45
    password: qwerDF@123
    port: 5672
    username: rabbitmqadmin
    virtual-host: /
