spring:
  rabbitmq:
    host: 47.111.165.45
    password: qwerDF@123
    port: 5672
    username: rabbitmqadmin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual # 配置 Consumer 手动提交
